### ISSUE TITLE
Turn on the blog

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix-docs#117]
As described in the Notion page for [product engineering blogs](https://www.notion.so/syntasso/10585a0225cc80a1ae77f1aeb83f6b79?v=fff85a0225cc818e8bcf000c4982ceab), some pieces of content don't make sense to go on the [Syntasso blog](https://www.syntasso.io/blog) as they are low-level, technical, and are probably not super useful to people who are reading the rest of the content there. 

For those kinds of features we want to turn on the docusaurus blog, where we can share both kratix and SKE features that are worth knowing about.

### Done when
- [x] Existing placeholder blogs have been deleted
- [ ] Blog is visible on docs.kratix.io (but probably empty)
- [x] Team know how to share content to the new blog

**Comment by kirederik** [comment]
Blog landing page

![Image](https://github.com/user-attachments/assets/46a591d8-0b36-40df-9487-fee795c030a0)

A blog post:

![Image](https://github.com/user-attachments/assets/ff759702-ba3b-471f-90b9-a18f20304ba8)

**Comment by kirederik** [comment]
not live yet until the pr gets merged

**Comment by kirederik** [comment]
how to blog on docusaurus: https://docusaurus.io/docs/blog
