### ISSUE TITLE
Blog: Publish a blog on decompressing works when debugging Kratix

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix-docs#119]
As introduced in [the feature on reducing works size](https://github.com/syntasso/kratix/issues/226), users debugging kratix will now need to decompress the workplacement contents. We will be describing how to do this to docs, but to make it easier for someone to know when they might come across this, we want a technical blog that describes:
1. When to check the works if you get an error in kratix
2. How to decompress the bits you need to decompress
3. What the contents mean and some actions you might need to take based on that fact.

### Done when
- [x] Blog reviewed by someone in the team
- [x] Blog published to kratix.io

**Comment by abangser** [comment]
The high level of this has been mentioned in our troubleshooting docs already: https://docs.kratix.io/main/troubleshooting#documents-are-not-appearing-in-my-destination

**Comment by kirederik** [comment]
for the lazy around you 
![Image](https://github.com/user-attachments/assets/83dc679c-841b-4b0d-b7d2-222fc69b1f71)
