### ISSUE TITLE
Suggestion: Harmonize install manifest for a single-node cluster.

### ISSUE THREAD

**Issue by stuartpreston** [syntasso/kratix-docs#15]
Followup from conversation at Configuration Management Camp in Ghent.

In the [Getting Started](https://kratix.io/docs/main/quick-start) guide, the URL to install Kratix for a 'single-node' is `https://raw.githubusercontent.com/syntasso/kratix/main/distribution/single-cluster/install-all-in-one.yaml`

In the [Single Cluster](https://kratix.io/docs/main/guides/installing-kratix/single-cluster-with-minikube) page the URL is `https://raw.githubusercontent.com/syntasso/kratix/main/distribution/kratix.yaml` with a follow-up Minio install.

Both approaches appear to work fine (I am testing with my own cloud-based single node) but it felt to me having fewer listed install manifests would make it simpler for the new user to understand. 

cc @winnab

**Comment by winnab** [comment]
Thank you @stuartpreston! We'll take a look!

**Comment by kirederik** [comment]
thanks for the feedback @stuartpreston !

we updated the single cluster page to use the bundled yaml, but also added the step-by-step under an "alternative installation" box, so people that prefer to see the individual packages can still do it.

closing this one for now
