### ISSUE TITLE
Document how to pull private image using node level permissions

### ISSUE THREAD

**Issue by abangser** [syntasso/kratix-docs#41]
The SKE Backstage Generator is the first private image we are handing to customers. For them to run this image in their own Kubernetes clusters they will need to provide read access to the image.

So far we have managed to do this through a local pull and load process which works for any Kubernetes cluster running in Docker locally (e.g. KinD, MiniKube, and K3s). When using cloud clusters this is not possible.

To pull from a [private registry in Kubernetes you have three core options](https://gtsopour.medium.com/aws-elastic-container-registry-ecr-is-a-fully-managed-container-registry-7624781635d9#:~:text=Using%20a%20private%20AWS%20ECR%20registry%20in%20Kubernetes):
1. Node level permissions
2. Pre-pulled images
3. Pod level permissions

Today, without doing extensions to Kratix, we users can do either option 1 or 2. Option 2 is basically a subset of option 1 just with more faff so we are going to propose to users today to follow option 1.

This is not ideal because node level permissions have a wide blast radius so we would prefer option 3, but this is captured in a [future enhancement](https://github.com/syntasso/kratix/issues/89). For this documentation, aim to lean heavily on the Kubernetes provided docs rather than customising as this is a standard Kubernetes administration option.

**Comment by kirederik** [comment]
Current docs:

![Image](https://github.com/syntasso/kratix-docs/assets/201163/9707c816-cd7b-4eaa-abe2-b274a8e25b0e)

The link points to: https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry

**Comment by catmo-syntasso** [comment]
We have agreed this is a k8s thing, so point to their docs.
