### ISSUE TITLE
feat: document how to use multiple workflows

### ISSUE THREAD

**Issue by SaphMB** [syntasso/kratix-docs#42]
This should be competed the completion of the work to introduce multiple configure workflows:
- https://github.com/syntasso/kratix/issues/90
- https://github.com/syntasso/kratix/issues/91

The documentation of workflows should be updated to reflect how users can specify multiple as well as an essentials information they should know. Namely, the order of execution and the need for names to be unique. The following reference pages should be updated:
- [Workflows reference](https://docs.kratix.io/main/reference/workflows)
- [Promise workflows](https://docs.kratix.io/main/reference/promises/workflows)
- [Resource workflows](https://docs.kratix.io/main/reference/resources/workflows)

**Comment by richcooper95** [comment]
Blocked on the feature being released (https://github.com/syntasso/kratix/issues/90)

Not implementing https://github.com/syntasso/kratix/issues/91 as part of this story (this PR ensures the need for uniqueness in names is documented, so we can follow up with validation later)
