### ISSUE TITLE
docs: Add page describing SLAs and support process

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix-docs#68]
As a **platform engineer using Kratix** 
I want **to see SLA and support stats on the Kratix/Syntasso website** 
So that **I know what to expect from operational support** 

----
**NB:** This should be a new page, please.

**Comment by cghsystems** [comment]
@Cat  I’m unsure we have enough shared context to pick it up. The story mentions stats, we don’t have stats yet, as we don’t track SLAs, as technically we don’t have any SLAs yet. All we have is the design if a system that derives from the Natwest contract. 

Given this, are you happy for us to start with a page documenting the headlines of the SLAs that we are putting place and for us to iterate towards publishing stats etc overtime as we start to track them? I.e we can talk today about: 
- Our monitored public Slack 
- UK Business Hours support (if we you need more that this then contact us etc)
- Respond to level 1 issues wthin X, Level 2 with Y
- Daily releases of SKE containing bug fixes and enhancements 
- Possibly others

Also, did you have any thoughts about where you would like this content to live?  The SLA and support process is technically SKE not OSS Kratix and therefore we do not want to publish on Kratix.io. SLAs and support processes are a kind of SKE marketing and we don’t have a public SKE page to drop this type of information onto (yet!). One simple solution is to drop this on to a new page under the hidden SKE section of the site (which is not discoverable). Any strong opinions?

**Comment by catmo-syntasso** [comment]
Yep - very happy with that approach for now! We could put something under [docs](https://docs.kratix.io/ske)? And then migrate over once CA tell us where syntasso stuff is going to go?
