### ISSUE TITLE
Write and publish a GCP SQL Promise

### ISSUE THREAD

**Issue by aclevername** [syntasso/kratix-docs#76]
Write a super simple GCP sql-as-a-service promise that can be used in the demo recording for #72. In the workflow just use the simplest tool possible, e.g. gcp cli or terraform apply. Write a delete pipeline as well for tearing it down. the demo we want to show:

1. installing promise
2. making a request with a basic config e.g. DB size
3. showing the thing being created in the UI

we don't need to make it any more fancy than that.

Publish in a repo so that we can link to it from the video and the docs. Marketplace may or may not be the correct place for this, chat with team

**Comment by aclevername** [comment]
@kirederik @abangser thoughts for where to put it?

**Comment by kirederik** [comment]
i'd vote for the marketplace repository; maybe in a subdirectory per cloud?

**Comment by kirederik** [comment]
it looks like the promise wasn't "published" to the marketplace; any reason why?

i can include it as part of #77 if you just missed this point

**Comment by aclevername** [comment]
@kirederik ah I forgot think about `kratix.io/marketplace`, its in the repo itself. Please feel free to add it 😄

**Comment by kirederik** [comment]
![Image](https://github.com/syntasso/kratix-docs/assets/201163/4c16585e-96c2-4e47-ae92-c29717c1d113)

added to the marketplace
