### ISSUE TITLE
Write and publish a AWS RDS Promise

### ISSUE THREAD

**Issue by aclevername** [syntasso/kratix-docs#77]
Write a super simple AWS sql-as-a-service promise that can be used in the demo recording for #73 . In the workflow just use the simplest tool possible, e.g. aws cli or terraform apply. Write a delete pipeline as well for tearing it down. the demo we want to show:

1. installing promise
2. making a request with a basic config e.g. DB size
3. showing the thing being created in the UI

we don't need to make it any more fancy than that.

Publish in a repo so that we can link to it from the video and the docs. Marketplace may or may not be the correct place for this, chat with team

**Comment by kirederik** [comment]
https://github.com/syntasso/kratix-marketplace/tree/main/sql/aws
