### ISSUE TITLE
Improve structure of docs.kratix.io/ske

### ISSUE THREAD

**Issue by catmo-syntasso** [syntasso/kratix-docs#89]
Similar to reordering that happened here in #88 

New should be:
- Introduction
- SKE
  - Introduction
  - Installation
-  Integrations 
  - Introduction (incl. update to page to reference TFE) 
  - Backstage
    - <Backstage sub-pages>
  - Terraform Enterprisese
- Support policy

**Comment by kirederik** [comment]
i don't think the proposed structure makes sense 👀 

is it supposed to be

* Introduction
* SKE
    * Introduction
    * Installation
* Integrations
    * Introduction (incl. update to page to reference TFE)
    * Backstage
    * Terraform Enterprisese
* Support policy

?

**Comment by catmo-syntasso** [comment]
Yes that was the intended structure, i can't use markdown
